name: crypto ETL pipeline

on:
  push:
      
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 5 * * *"
jobs:
  run-etl:
    runs-on: ubuntu-latest
    environment: Env
    permissions:
      contents: read
      
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
      GECKO_API_KEY: ${{ secrets.GECKO_API_KEY }}
      NEON_POSTGRES: ${{ secrets.NEON_POSTGRES }}
      SLACK_WEB_HOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
<<<<<<< HEAD
      
=======
>>>>>>> 6aeb018 (Set up ETL GitHub Actions with cron, cache, and Slack alerts)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: cache pip 
        uses: actions/cache@v3
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest tests/

      - name: Run ETL workflow
        run: python -m src.main
        
<<<<<<< HEAD
      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEB_HOOK_URL }}
          message: "Crypto ETL workflow completed successfully!"
          status: Success
      - name: Slack Notification failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEB_HOOK_URL }}
          message: "Crypto Etl Workflow failed"
          status: failure
          
 
        
=======
      
>>>>>>> 6aeb018 (Set up ETL GitHub Actions with cron, cache, and Slack alerts)
